### ISSUE TITLE
version 3.9.4 doesn't work. 3.8.7 version works very well.

### ISSUE THREAD

**Issue by haohighview** [martijn00/InteractiveMediaAdsXamarin#2]
11-13 12:39:07.079 I/MonoDroid(18981): UNHANDLED EXCEPTION:
11-13 12:39:07.087 I/MonoDroid(18981): System.TypeLoadException: VTable setup of type Com.Google.Android.Exoplayer2.Ext.Ima.ImaAdsLoader failed
11-13 12:39:07.087 I/MonoDroid(18981):   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x0001b] in <43dbbdc147f2482093d8409abb04c233>:0 
11-13 12:39:07.087 I/MonoDroid(18981):   at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0007a] in <43dbbdc147f2482093d8409abb04c233>:0 
11-13 12:39:07.087 I/MonoDroid(18981):   at System.Reflection.MonoCMethod.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <43dbbdc147f2482093d8409abb04c233>:0 
11-13 12:39:07.087 I/MonoDroid(18981):   at System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) [0x00000] in <43dbbdc147f2482093d8409abb04c233>:0 
11-13 12:39:07.087 I/MonoDroid(18981):   at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00056] in <4d996bab56b14864b2a1299fea73b3fe>:0 
11-13 12:39:07.087 I/MonoDroid(18981):   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00116] in <4d996bab56b14864b2a1299fea73b3fe>:0 
11-13 12:39:07.087 I/MonoDroid(18981):   at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000c1] in <4d996bab56b14864b2a1299fea73b3fe>:0 
11-13 12:39:07.087 I/MonoDroid(18981):   at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <4d996bab56b14864b2a1299fea73b3fe>:0 
11-13 12:39:07.087 I/MonoDroid(18981):   at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <4d996bab56b14864b2a1299fea73b3fe>:0 
11-13 12:39:07.087 I/MonoDroid(18981):   at Java.Lang.Reflect.Constructor.NewInstance (Java.Lang.Object[] initargs) [0x0003d] in <4d996bab56b14864b2a1299fea73b3fe>:0 
11-13 12:39:07.087 I/MonoDroid(18981):   at MvxStandardTemplate.Droid.ExoPlayer.ExoPlayerManager.CreateAdsMediaSource (Com.Google.Android.Exoplayer2.Source.IMediaSource mediaSource, Android.Net.Uri adTagUri) [0x00060] in D:\DataHaoZhang\TFSProjects\HMediaApp\MvxStandardTemplate\MvxStandardTemplate.Android\ExoPlayer\ExoPlayerManager.cs:211 
11-13 12:39:07.087 I/MonoDroid(18981):   at MvxStandardTemplate.Droid.ExoPlayer.ExoPlayerManager.PrepareExoPlayer (System.String url) [0x00053] in D:\DataHaoZhang\TFSProjects\HMediaApp\MvxStandardTemplate\MvxStandardTemplate.Android\ExoPlayer\ExoPlayerManager.cs:121 
11-13 12:39:07.087 I/MonoDroid(18981):   at MvxStandardTemplate.Droid.ExoPlayer.ExoPlayerManager.PreparePlayer (System.String url) [0x0000e] in D:\DataHaoZhang\TFSProjects\HMediaApp\MvxStandardTemplate\MvxStandardTemplate.Android\ExoPlayer\ExoPlayerManager.cs:93 
11-13 12:39:07.087 I/MonoDroid(18981):   at MvxStandardTemplate.Droid.ExoPlayer.ExoPlayerLayout.ClickToStart () [0x00063] in D:\DataHaoZhang\TFSProjects\HMediaApp\MvxStandardTemplate\MvxStandardTemplate.Android\ExoPlayer\ExoPlayerLayout.cs:149 
11-13 12:39:07.087 I/MonoDroid(18981):   at MvxStandardTemplate.Droid.Renderer.VideoPlayerRenderer.SetPlayer () [0x000e6] in D:\DataHaoZhang\TFSProjects\HMediaApp\MvxStandardTemplate\MvxStandardTemplate.Android\Renderer\VideoPlayerRenderer.cs:47 
11-13 12:39:07.087 I/MonoDroid(18981):   at MvxStandardTemplate.Droid.Renderer.VideoPlayerRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00031] in D:\DataHaoZhang\TFSProjects\HMediaApp\MvxStandardTemplate\MvxStandardTemplate.Android\Renderer\VideoPlayerRenderer.cs:97 
11-13 12:39:07.087 I/MonoDroid(18981):   at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
11-13 12:39:07.087 I/MonoDroid(18981):   at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:150 
11-13 12:39:07.087 I/MonoDroid(18981):   at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:370 
11-13 12:39:07.087 I/MonoDroid(18981):   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00114] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:623 
11-13 12:39:07.087 I/MonoDroid(18981):   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:417 
11-13 12:39:07.087 I/MonoDroid(18981):   at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) [0x00225] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:173 
11-13 12:39:07.087 I/MonoDroid(18981):   at Xamarin.Forms.BindingExpression.Apply (System.Boolean fromTarget) [0x0003e] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:57 
11-13 12:39:07.087 I/MonoDroid(18981):   at Xamarin.Forms.BindingExpression+BindingExpressionPart.<PropertyChanged>b__49_0 () [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindingExpression.cs:615 
11-13 12:39:07.087 I/MonoDroid(18981):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <4d996bab56b14864b2a1299fea73b3fe>:0 
11-13 12:39:07.087 I/MonoDroid(18981):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <4d996bab56b14864b2a1299fea73b3fe>:0 
11-13 12:39:07.088 I/MonoDroid(18981):   at (wrapper dynamic-method) System.Object.41(intptr,intptr)
11-13 12:39:07.124 I/art     (18981): Starting a blocking GC Explicit
11-13 12:39:07.145 I/art     (18981): Explicit concurrent mark sweep GC freed 11560(691KB) AllocSpace objects, 4(72KB) LOS objects, 23% free, 52MB/68MB, paused 443us total 21.222ms
11-13 12:39:07.149 D/Mono    (18981): GC_TAR_BRIDGE bridges 583 objects 15329 opaque 6134 colors 491 colors-bridged 440 colors-visible 440 xref 123 cache-hit 0 cache-semihit 0 cache-miss 51 setup 0.08ms tarjan 6.08ms scc-setup 0.15ms gather-xref 0.03ms xref-setup 0.01ms cleanup 0.49ms
11-13 12:39:07.149 D/Mono    (18981): GC_BRIDGE: Complete, was running for 28.77ms
11-13 12:39:07.149 D/Mono    (18981): GC_MAJOR: (LOS overflow) time 26.66ms, stw 27.97ms los size: 17408K in use: 2832K
11-13 12:39:07.149 D/Mono    (18981): GC_MAJOR_SWEEP: major size: 7248K in use: 5016K
11-13 12:39:07.150 E/AppCenterCrashes(18981): Unhandled Exception from source=AndroidEnvironment
11-13 12:39:07.150 E/AppCenterCrashes(18981): System.TypeLoadException: VTable setup of type Com.Google.Android.Exoplayer2.Ext.Ima.ImaAdsLoader failed
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x0001b] in <43dbbdc147f2482093d8409abb04c233>:0 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0007a] in <43dbbdc147f2482093d8409abb04c233>:0 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at System.Reflection.MonoCMethod.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <43dbbdc147f2482093d8409abb04c233>:0 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) [0x00000] in <43dbbdc147f2482093d8409abb04c233>:0 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00056] in <4d996bab56b14864b2a1299fea73b3fe>:0 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00116] in <4d996bab56b14864b2a1299fea73b3fe>:0 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000c1] in <4d996bab56b14864b2a1299fea73b3fe>:0 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <4d996bab56b14864b2a1299fea73b3fe>:0 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <4d996bab56b14864b2a1299fea73b3fe>:0 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at Java.Lang.Reflect.Constructor.NewInstance (Java.Lang.Object[] initargs) [0x0003d] in <4d996bab56b14864b2a1299fea73b3fe>:0 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at MvxStandardTemplate.Droid.ExoPlayer.ExoPlayerManager.CreateAdsMediaSource (Com.Google.Android.Exoplayer2.Source.IMediaSource mediaSource, Android.Net.Uri adTagUri) [0x00060] in D:\DataHaoZhang\TFSProjects\HMediaApp\MvxStandardTemplate\MvxStandardTemplate.Android\ExoPlayer\ExoPlayerManager.cs:211 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at MvxStandardTemplate.Droid.ExoPlayer.ExoPlayerManager.PrepareExoPlayer (System.String url) [0x00053] in D:\DataHaoZhang\TFSProjects\HMediaApp\MvxStandardTemplate\MvxStandardTemplate.Android\ExoPlayer\ExoPlayerManager.cs:121 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at MvxStandardTemplate.Droid.ExoPlayer.ExoPlayerManager.PreparePlayer (System.String url) [0x0000e] in D:\DataHaoZhang\TFSProjects\HMediaApp\MvxStandardTemplate\MvxStandardTemplate.Android\ExoPlayer\ExoPlayerManager.cs:93 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at MvxStandardTemplate.Droid.ExoPlayer.ExoPlayerLayout.ClickToStart () [0x00063] in D:\DataHaoZhang\TFSProjects\HMediaApp\MvxStandardTemplate\MvxStandardTemplate.Android\ExoPlayer\ExoPlayerLayout.cs:149 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at MvxStandardTemplate.Droid.Renderer.VideoPlayerRenderer.SetPlayer () [0x000e6] in D:\DataHaoZhang\TFSProjects\HMediaApp\MvxStandardTemplate\MvxStandardTemplate.Android\Renderer\VideoPlayerRenderer.cs:47 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at MvxStandardTemplate.Droid.Renderer.VideoPlayerRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00031] in D:\DataHaoZhang\TFSProjects\HMediaApp\MvxStandardTemplate\MvxStandardTemplate.Android\Renderer\VideoPlayerRenderer.cs:97 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:150 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:370 
11-13 12:39:07.150 E/AppCenterCrashes(18981):   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject

**Comment by martijn00** [comment]
For 1 you need to fill out the issue template. Otherwise i won't be able to help. For 2 the exoplayer has not been updated to this version yet, 2.9.1 will contain this, but is not really usable without the latest Xamarin alpha.
