### ISSUE TITLE
Could not pass build

### ISSUE THREAD

**Issue by haohighview** [martijn00/InteractiveMediaAdsXamarin#3]
### Expected behavior
2>D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error XA4215:   `mono.com.google.ads.interactivemedia.v3.api.AdErrorEvent_AdErrorListenerImplementor` generated by: Com.Google.Ads.Interactivemedia.V3.Api.IAdErrorEventAdErrorListenerImplementor, InteractivemediaAds, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2>D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error XA4215:   `mono.com.google.ads.interactivemedia.v3.api.AdErrorEvent_AdErrorListenerImplementor` generated by: Com.Google.Ads.Interactivemedia.V3.Api.IAdErrorEventAdErrorListenerImplementor, InteractivemediaAds, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2>D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error XA4215: The Java type `mono.com.google.ads.interactivemedia.v3.api.AdEvent_AdEventListenerImplementor` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
2>D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error XA4215:   `mono.com.google.ads.interactivemedia.v3.api.AdEvent_AdEventListenerImplementor` generated by: Com.Google.Ads.Interactivemedia.V3.Api.IAdEventAdEventListenerImplementor, InteractivemediaAds, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2>D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error XA4215:   `mono.com.google.ads.interactivemedia.v3.api.AdEvent_AdEventListenerImplementor` generated by: Com.Google.Ads.Interactivemedia.V3.Api.IAdEventAdEventListenerImplementor, InteractivemediaAds, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2>D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error XA4215: The Java type `mono.com.google.ads.interactivemedia.v3.api.AdsLoader_AdsLoadedListenerImplementor` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
2>D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error XA4215:   `mono.com.google.ads.interactivemedia.v3.api.AdsLoader_AdsLoadedListenerImplementor` generated by: Com.Google.Ads.Interactivemedia.V3.Api.IAdsLoaderAdsLoadedListenerImplementor, InteractivemediaAds, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2>D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error XA4215:   `mono.com.google.ads.interactivemedia.v3.api.AdsLoader_AdsLoadedListenerImplementor` generated by: Com.Google.Ads.Interactivemedia.V3.Api.IAdsLoaderAdsLoadedListenerImplementor, InteractivemediaAds, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2>D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error XA4215: The Java type `mono.com.google.ads.interactivemedia.v3.api.CompanionAdSlot_ClickListenerImplementor` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
2>D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error XA4215:   `mono.com.google.ads.interactivemedia.v3.api.CompanionAdSlot_ClickListenerImplementor` generated by: Com.Google.Ads.Interactivemedia.V3.Api.ICompanionAdSlotClickListenerImplementor, InteractivemediaAds, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2>D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2342,3): error XA4215:   `mono.com.google.ads.interactivemedia.v3.api.CompanionAdSlot_ClickListenerImplementor` generated by: Com.Google.Ads.Interactivemedia.V3.Api.ICompanionAdSlotClickListenerImplementor, InteractivemediaAds, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

**Version:** 1.x
VS2019 16.1.3
Xam.Plugins.Android.Interactivemedia.Ads  3.10.6
Xam.Plugins.Android.ExoPlayer.Core 2.9.6
**Platform:** 
- [ ] :robot: Android

**Comment by martijn00** [comment]
You need to set the dex compiler to d8 in the android options so java 1.8 support is enabled.

**Comment by haohighview** [comment]
![image](https://user-images.githubusercontent.com/8456671/59414411-095ae800-8df4-11e9-927b-c1e48ec845a6.png)

**Comment by haohighview** [comment]
doesn't work
